### ISSUE TITLE
'by' attribute on iq error from bare host invalid

### ISSUE THREAD

**Issue by Zash** [matrix-org/matrix-bifrost#100]
Sending a [XMPP Ping](https://xmpp.org/extensions/xep-0199.xml) like this:

```xml
<iq type="get" to="matrix.org" id="lx3">
  <ping xmlns="urn:xmpp:ping"/>
</iq>
```

Returns me this:

```xml
<iq type="error" from="matrix.org" id="lx3" xml:lang="en">
  <error by="@matrix.org" type="cancel">
    <not-acceptable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
  </error>
</iq>
```

The `@by` attribute contains an invalid JID with an empty node-part. Just `by="matrix.org"` would be appropriate here.

Secondary, that this returns an error at all. Pings like this are common for server-to-server keepalive and detection of stalled connections.

**Comment by Half-Shot** [comment]
Oh fun. The @ is certainly unintentional. 

Secondly. We don't support S2S pings yet which is probably why you get funky results back. I guess we should do that.
