### ISSUE TITLE
Causing Dino to ping about every message due to standards incompliance

### ISSUE THREAD

**Issue by Mikaela** [matrix-org/matrix-bifrost#119]
> The issue seems to be a standart-incompliance of Bifröst (or rather multiple ones). Please open an issue at Bifröst.
> 
> When an XMPP client joins a room, it sends a presence to `room@example.com/desired_nickname`. The MUC is then supposed to send the presences of the other occupants, followed by the "self presence".
> 
> > After a client sends presence to join a room, the MUC service MUST send it events in the following order: 1. In-room presence from other occupants 2. In-room presence from the joining entity itself (so-called "self-presence") [...] [From XEP-0045]
> 
> > [...] the "self-presence" sent by the room to the new user MUST include a status code of 110 so that the user knows this presence refers to itself as an occupant. [From XEP-0045]
> 
> However, the reflected presence from the Bifröst room, does not include the 110 status code, thus XMPP clients can't know that this is their own presence, and thus don't know that they succeeded in the room. The XMPP client can't just assume that a presence from ` room@example.com/desired_nickname` is their self-presence because
> 
> > The service MAY rewrite the new occupant's roomnick (e.g., if roomnicks are locked down or based on some other policy). [From XEP-0045]
> 
> The problems you describe arise because Dino doesn't know that it succeeded in joining the room and which its nick in the room is. I made a few changes such that Dino handles the issue of unknown-join-status more reasonably ([13d3d2a](https://github.com/dino/dino/commit/13d3d2aca6f5975bbf16ba56b7cd0c4e2008e936)), but there will still be issues until Bifröst fixes the self-presence sending.
> 
> Note that I was only able to see the faulty self presence once. The room now ignores my subsequent join-attempts (thus also doesn't reflect my presence at all), while however still sending me messages. So in general, you'll probably see a number of issues with Bifröst rooms, however in most cases it's probably not the client's fault.

* https://github.com/dino/dino/issues/746#issuecomment-613479826

I don't understand the issue well enough to describe it in my own words.

**Comment by uhoreg** [comment]
Testing this, it looks like bifrost now sends a status of 110 on the self-presence:

```
<presence xmlns="jabber:client" from="#bifrost#matrix.org@matrix.org/uhoreg_xmpp" to="hubert@uhoreg.ca/RBWCH83P">
<x xmlns="http://jabber.org/protocol/muc#user">
<status code="110" />
<status code="100" />
<status code="170" />
<item affiliation="member" role="participant" />
</x>
</presence>
```

so I think this can be closed
