### ISSUE TITLE
Use XMPP-submitted nickname as user name in matrix room

### ISSUE THREAD

**Issue by ge0rg** [matrix-org/matrix-bifrost#153]
When an XMPP client joins, it will send the desired nickname as the resource part of the occupant JID, "Ge0rG" in the example:

```xml
<presence id="0754d69f7bab4374a473c57d91b227c1" xml:lang="en" to="#bifrost#matrix.org@matrix.org/Ge0rG">
  <x xmlns="http://jabber.org/protocol/muc"><history seconds="130"/></x>
</presence>
```

This nickname should also be represented as the participant's name on the matrix side of the room. However, The user's real JID local part ("georg") is used instead.

**Comment by Half-Shot** [comment]
Matrix supports per room displaynames, so we should use those.
