### ISSUE TITLE
Silent-fail to join matrix chat from XMPP when nickname in room is already taken

### ISSUE THREAD

**Issue by JuniorJPDJ** [matrix-org/matrix-bifrost#212]
**Describe the bug**
Silent-fail to join matrix chat from XMPP when nickname in room is already taken.
No prompt nor error on xmpp side, it just silent fail it.
Gajim freezes on Joining and conversations have empty chat, messages are not getting bridged.
After changing nickname in XMPP (conversations allows that, gajim doesn't afaik) room is being joined successfully.

**Comment by unclechu** [comment]
Duplicate of #204

**Comment by JuniorJPDJ** [comment]
True, thanks.
