### ISSUE TITLE
XMPP -> Matrix edits

### ISSUE THREAD

**Issue by JuniorJPDJ** [matrix-org/matrix-bifrost#214]
Now all xmpp edits are shown as new message in matrix

**Comment by unclechu** [comment]
Cannot reproduce on matrix.org:
![2020-12-02 06-47-06](https://user-images.githubusercontent.com/799353/100829525-3f69ad00-346a-11eb-8364-725f6b6448f1.png)

**Comment by JuniorJPDJ** [comment]
Yes, it seem to work now.
Maybe bridge got restarted.
