### ISSUE TITLE
Join XMPP MUCs from Matrix

### ISSUE THREAD

**Issue by JuniorJPDJ** [matrix-org/matrix-bifrost#215]
**Is your feature request related to a problem? Please describe.**
I've some XMPP group chats I'd like to follow, now matrix is my central point of communication..
If I just could join this XMPP chats from Matrix it would be ideal solution ;o
Using purple in that case seems as bad solution as we have that beautiful bridge ;3

**Comment by Mikaela** [comment]
Isn't this already possible?

* https://github.com/matrix-org/matrix-bifrost/wiki/Address-syntax#matrix---xmpp

**Comment by JuniorJPDJ** [comment]
It is, sorry and thanks ;)
