### ISSUE TITLE
Homeserver crashes due to user permissions

### ISSUE THREAD

**Issue by robertfoss** [matrix-org/matrix-bifrost#24]
Commit: `054526dacd2dfcea47a07dda1971b7fbb45e00ed`

I'm seeing crashes while running the systemd service as a non-root user.
Unfortunately I'm not seeing any logs.

Running as the user `matrix-synapse` causes the service to enter a restart-loop, but `root` starts properly. This also wasn't an issue before registering the appservice.

**Comment by Cadair** [comment]
Are the permissions on your appservice config file set correctly for the matrix-synapse user?

**Comment by robertfoss** [comment]
Yeah, I did a `chown -R matrix-synapse $REPO_DIR`. However it still belongs to another group.

**Comment by robertfoss** [comment]
Possibly accounts.xml belonged to the wrong group still

**Comment by jaller94** [comment]
Hi Robert,
So much has happened in Synapse since 2018.. I'm going to close this without an investigation.
