### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by thegodtune** [matrix-org/matrix-bifrost#301]
Hi, I request that you kindly **enable discussion** on this repository because I have a couple of questions I would love to ask concerning your implementation of the XMPP protocols.
I am Ajayi Olatunji from the Debian Project, we are trying to implement [xmpp 0313 protocol](https://xmpp.org/extensions/xep-0313.html) so that folks connecting to the network from xmpp side will be able to access offline messages just the way folks connecting via matrix already do.
Myself and my partner who we are handling the project together  decided to reach out to as many people and organizations as possible who we feel have done something relating to what we are trying to implement.
Every help from you will be very much appreciated by the Debian Project.
Thank you.

**Comment by Half-Shot** [comment]
Hi there, sorry this took so long for me to get back to. We're opting to not use discussions for the moment in favor of the Matrix room (to avoid too many places  for discussions).

Feel free to reach out in there to ask questions :)
