### ISSUE TITLE
user avatar

### ISSUE THREAD

**Issue by muppeth** [matrix-org/matrix-bifrost#59]
As a user I would like to see avatars on xmpp and matrix users in the room.

**Comment by Half-Shot** [comment]
I believe this is now fixed.

**Comment by Bubu** [comment]
Is this deployed? I don't see any avatars across the bridge, neither XMPP -> matrix not matrix -> Xmpp.

**Comment by Gigadoc2** [comment]
It seems that the bridge confuses the user avatar with the room avatar. At least, the XMPP puppets are all shown with the avatar of the MUC.
