### ISSUE TITLE
Official bridge does not work since several months

### ISSUE THREAD

**Issue by Neustradamus** [matrix-org/matrix-bifrost#73]
The official bridge does not work, can you launch it?

Thanks in advance.

**Comment by Neustradamus** [comment]
When it will be here again?

**Comment by moppman** [comment]
Seems to be back ["pretty soon"](https://nitter.net/matrixdotorg/status/1181257728678866950)

**Comment by Neustradamus** [comment]
For Christmas 2019, it will be here?

**Comment by Neustradamus** [comment]
Happy New Year 2020 ^^

**Comment by Half-Shot** [comment]
This is now fixed. The bridge can be found at just `matrix.org`

**Comment by Mikaela** [comment]
Is https://github.com/matrix-org/matrix-bifrost/wiki/Address-syntax stilll up-to-date?

**Comment by licaon-kter** [comment]
@Mikaela #room#domain.tld@matrix.org appears to work

**Comment by Neustradamus** [comment]
@Half-Shot: Thanks for this change but there are always problems:
- impossible to see vCard of an user@matrix.org (matrix.org registred users) and other servers too except your personal server ;)
- 1:1 chat does not work

**Comment by licaon-kter** [comment]
@Neustradamus 
> impossible to join #matrix# matrix.org@matrix.org

I've tested yesterday from my Conversejs instance and works fine. What's your error?
