### ISSUE TITLE
Gateways should use the real JID of users in the matrix membership

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-bifrost#81]
Matrix rooms aren't anonymous, so we shouldn't really pretend that they are

**Comment by Half-Shot** [comment]
This is partially fixed. For some reason, profiles aren't applying X->M

**Comment by licaon-kter** [comment]
> In addition, we also notify XMPP users that the room is both logged and non-anonymous so they won't be surprised to know matrix users can read the history forever etc.

I don't see any announcement at all on join.

Eg. Conversations has this for a while now: https://github.com/siacs/Conversations/commit/1a1bfb324672994daceacbe468d84cae4dfe4077

![Qq7tvaIkT9mNIT9TnXRadQ](https://user-images.githubusercontent.com/2282799/74449991-4e4c8800-4e75-11ea-97d9-de948d018255.jpg)

But I'm not seeing this triggered for bridged rooms via matrix.org

**Comment by Half-Shot** [comment]
We send it on join, but not before: https://github.com/matrix-org/matrix-bifrost/blob/develop/src/xmppjs/XJSGateway.ts#L407-L410

I guess there needs to be a mechanism to pre-warn, but I'm not aware of such a thing?

**Comment by licaon-kter** [comment]
I deleted the bookmark and then readded it, isn't that "join" or what does join mean?

**Comment by Half-Shot** [comment]
Ah, yeah it could be and isn't yet.

**Comment by Half-Shot** [comment]
(This got done)

**Comment by licaon-kter** [comment]
And deployed?
