### ISSUE TITLE
Kick from Matrix room reflected incorrectly to XMPP

### ISSUE THREAD

**Issue by ge0rg** [matrix-org/matrix-bifrost#82]
When a user is removed from a Matrix room, the kicker and not the kicked person appears to vanish on the XMPP side.

From Matrix HQ:

As shown in Riot Web:

> TravisR (@travis:t2l.io) hat Ge0rG gekickt. Grund: xmpp bridge is dead

As shown over XMPP bridge:

> <--- TravisR has left the room

Received incorrect XML:

```xml
<presence from="#matrix#matrix.org@half-shot.uk/TravisR" to="georg@*stripped*" id="67f656e9-7162-4d36-9cc9-b034d3876d18-1DDFB" type="unavailable">
  <x xmlns="http://jabber.org/protocol/muc#user">
    <item role="none" affiliation="member"/>
  </x>
</presence>
```

Expected [correct XML](https://xmpp.org/extensions/xep-0045.html#example-91):

```xml
<presence from="#matrix#matrix.org@half-shot.uk/Ge0rG" to="georg@*stripped*" id="67f656e9-7162-4d36-9cc9-b034d3876d18-1DDFB" type="unavailable">
  <x xmlns="http://jabber.org/protocol/muc#user">
    <item role="none" affiliation="member">
      <actor nick="TravisR"/>
      <reason>Avaunt, you cullion</reason>
    </item>
    <status code='307'/>
  </x>
</presence>
```

**Comment by Half-Shot** [comment]
I believe we fixed this during the kick refactor.
